<?php

namespace App\Controllers\Zoho;

use App\Controllers\BaseController;
use App\Models\Zoho\ZohoClientModel;
use App\Models\Zoho\ZohoModel;
use App\Models\Zoho\ZohoTokenModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;
use CodeIgniter\I18n\Time;

class ZohoDashboardController extends BaseController
{
    protected $zoho;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

        $this->zoho = new ZohoModel(
            getenv('ZOHO_CLIENT_ID'),
            getenv('ZOHO_SECRET_US'),
            getenv('ZOHO_SECRET_EU'),
            getenv('ZOHO_REDIRECT_URL')
        );
    }

    public function index()
    {
        //
        $model = new ZohoTokenModel();
        $session = session();

        $data = [];
        $data['session'] = session();
        $data['zohoUrl'] = ZohoUtilsController::generateAuthorizationURL($this->zoho, 'state');

        if ($this->request->getGet('code')) {

            // se tiver CODE, habilitar a integração e gerar o token/refresh token e salvar na base
            $token = ZohoUtilsController::generateToken($this->zoho, $this->request->getGet('code'));

            $data = [
                'client_id' => $session->client_id,
                'access_token' => $token->getAccessToken(),
                'refresh_token' => $token->getRefreshToken(),
                'expires_in' => $token->getExpiresIn()
            ];

            $model->save($data);
        }


        return view('Zoho/dashboard/home', $data);




        $model = new ZohoModel();

        $newData = [
            'client_id' => getenv('ZOHO_CLIENT_ID'),
            'client_secret' => getenv('ZOHO_SECRET_US'),
            'install_uri' => $zohoUrl,
            'redirect_uri' => getenv('ZOHO_REDIRECT_URL'),
            'hapikey' => 'hapikey'
        ];

        $model->select('*');
        $model->where(['client_id' => getenv('ZOHO_CLIENT_ID')]);

        $date = $model->findAll();

        dd($date);

//        $model->save($newData);



        //
        return view('Zoho/dashboard/home');
    }

    public function generateToken()
    {
        $code = $this->request->getGet('code');

        if (isset($code)) {
            $token = ZohoUtilsController::generateToken($this->zohoClient, $code);

            d($token->getAccessToken());

            ZohoUtilsController::refreshToken($this->zohoClient, $token);

            d($token->getAccessToken());

            ZohoUtilsController::refreshToken($this->zohoClient, $token);

            d($token->getAccessToken());

            ZohoUtilsController::refreshToken($this->zohoClient, $token);

            d($token->getAccessToken());
        }

    }

    public function users()
    {
        //
        return view('Zoho/dashboard/users');
    }

    public function settings()
    {
        //
        return view('Zoho/dashboard/settings');
    }
}
